baseURL = 'https://da.vidh.art/'
languageCode = 'en-gb'
title = 'da.vidh.art'
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
copyright = "&copy; David Hart"
enableRobotsTXT = true
enableGitInfo = true

[Author]
    name = "David"

[params]
    description = "da.vidh.art"
    images = ["images/portrait.svg"] 

    [[params.links]]
        icon = "fas fa-envelope"
        url = "mailto: d [at] vidh.art"
        title = "email"

    [[params.links]]
        icon = "fab fa-github"
        url = "https://github.com/djh82"
        title = "github"

    [[params.links]]
        icon = "fab fa-instagram"
        url = "https://instagram.com/da.vidh.art"
        title = "instagram"

    [[params.links]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/da_vidh_art"
        title = "twitter"

[build]
  writeStats = true

[deployment]
    [[deployment.targets]]
        name = "deployment"
        URL = "s3://da.vidh.art?region=eu-west-2"
        cloudFrontDistributionID = "E25AW65XM98T01"

    [[deployment.matchers]]
        pattern = "(?i)^.+\\.(svg|ttf|woff|woff2|eot|png|jpg|gif|pdf|ico)$"
        cacheControl = "public, s-maxage=7776000, max-age=604800" #90d,7d

    [[deployment.matchers]]
        pattern = "^.+\\.(html|xml|json|txt)$"
        cacheControl = "public, s-maxage=604800, max-age=3600" #7d,1h

    [[deployment.matchers]]
        pattern = "^sitemap\\.xml$"
        cacheControl = "public, s-maxage=604800, max-age=86400" #7d,1d
        contentType = "application/xml"

    [[deployment.matchers]]
        pattern = "^.+\\.(css|js)$"
        cacheControl = "public, immutable, max-age=31536000" #1y