baseURL = 'https://da.vidh.art/'
languageCode = 'en-gb'
title = 'da.vidh.art'
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
copyright = "&copy; David Hart"
enableRobotsTXT = true
enableGitInfo = true

[Author]
    name = "David"

[params]
    description = "da.vidh.art"
    images = ["images/portrait.svg"] 

    [[params.links]]
        icon = "fas fa-envelope"
        url = "mailto: d [at] vidh.art"

    [[params.links]]
        icon = "fab fa-github"
        url = "https://github.com/djh82"

    [[params.links]]
        icon = "fab fa-instagram"
        url = "https://instagram.com/da.vidh.art"

    [[params.links]]
        icon = "fab fa-twitter"
        url = "https://twitter.com/da_vidh_art"

[build]
  writeStats = true

[deployment]
    [[deployment.targets]]
        name = "deployment"
        URL = "s3://da.vidh.art?region=eu-west-2"
        cloudFrontDistributionID ="E25AW65XM98T01"
