baseURL = 'https://da.vidh.art/'
languageCode = 'en-gb'
title = 'da.vidh.art'
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "David"
    portrait = "images/portrait.svg"

[params]
    description = "da.vidh.art"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/djh82"

    [params.colors]
        background = "#252627"
        foreground = "#bfbfbf"
        hover = "#f85e0cff"

[deployment]
    [[deployment.targets]]
        name = "deployment"
        URL = "s3://da.vidh.art?region=eu-west-2"
        cloudFrontDistributionID ="E25AW65XM98T01" 
