baseURL = 'https://da.vidh.art/'
languageCode = 'en-gb'
title = 'da.vidh.art'
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]
copyright = "&copy; David Hart"
enableRobotsTXT = true

[Author]
    name = "David"
    portrait = "images/portrait.svg"

[params]
    description = "da.vidh.art"
    customCss = "css/custom.css"

    [[params.links]]
        icon = "envelope"
        iconset = "fa"
        title = "Email"
        url = "mailto: d [at] vidh.art"

    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/djh82"

    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://instagram.com/da.vidh.art"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/da_vidh_art"

    [params.colors]
        background = "#101923"
        foreground = "#8f97a3"
        hover = "#FFCF43"

[deployment]
    [[deployment.targets]]
        name = "deployment"
        URL = "s3://da.vidh.art?region=eu-west-2"
        cloudFrontDistributionID ="E25AW65XM98T01"
        exclude = "images/portrait.jpg"
